/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ffos.rusija2018.view;
import ffos.rusija2018.controller.ObradaMjesto; 
import ffos.rusija2018.controller.ObradaEkipa;  
import ffos.rusija2018.controller.ObradaUtakmica;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.DefaultComboBoxModel;
import ffos.rusija2018.model.Utakmica;
import ffos.rusija2018.model.Ekipa;
import ffos.rusija2018.model.Mjesto;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import java.util.HashSet;


/**
 *
 * @author Sanja
 */
public class FormaUtakmice extends javax.swing.JFrame {
private ObradaUtakmica ou;
private ObradaEkipa oe;
private ObradaMjesto om;

    /**
     * Creates new form FormaUtakmice
     */
    public FormaUtakmice() {
        initComponents();
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);


ou= new ObradaUtakmica(); 
oe = new ObradaEkipa();  
om = new ObradaMjesto();


       DefaultComboBoxModel m = new DefaultComboBoxModel();
        for(Ekipa p : oe.getEkipe()){
            m.addElement(p);
        }
        domacin.setModel(m);
        
        ucitaj();
        
         DefaultComboBoxModel a = new DefaultComboBoxModel();
        for(Ekipa p : oe.getEkipe()){
            a.addElement(p);
        }
        gost.setModel(a);
        
        ucitaj();
        
         DefaultComboBoxModel n = new DefaultComboBoxModel();
        for(Mjesto p : om.getMjesta()){
            n.addElement(p);
        }
        mjesto.setModel(n);
        
        ucitaj();
        
        

    }
    
        private void ucitaj() {
        DefaultListModel m = new DefaultListModel();
        for (Utakmica p : ou.getUtakmice()) {
            m.addElement(p);
        }
        lista.setModel(m);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        domacin = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        gost = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        rezultat = new javax.swing.JTextField();
        mjesto = new javax.swing.JComboBox<>();
        dodaj = new javax.swing.JButton();
        promjeni = new javax.swing.JButton();
        obrisi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Rusija 2018 Utakmice");

        lista.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lista);

        jLabel1.setText("Domaćin");

        domacin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Mjesto");

        jLabel3.setText("Gost");

        gost.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Rezultat");

        mjesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        dodaj.setText("Dodaj");
        dodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajActionPerformed(evt);
            }
        });

        promjeni.setText("Promijeni");
        promjeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promjeniActionPerformed(evt);
            }
        });

        obrisi.setText("Obriši");
        obrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obrisiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1)
                                .addComponent(domacin, 0, 164, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addComponent(gost, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addComponent(rezultat)
                                .addComponent(mjesto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dodaj)
                                .addGap(18, 18, 18)
                                .addComponent(promjeni))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(obrisi)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mjesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(domacin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rezultat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dodaj)
                            .addComponent(promjeni))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(obrisi)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajActionPerformed
        // TODO add your handling code here:
        Utakmica i = new Utakmica();
        
        i.setRezultat(rezultat.getText());
        i.setDomacin((Ekipa)domacin.getSelectedItem());
        i.setGost((Ekipa)gost.getSelectedItem());
        i.setMjesto((Mjesto)mjesto.getSelectedItem());
        ou.dodaj(i);
        ucitaj();

        
    }//GEN-LAST:event_dodajActionPerformed

    private void promjeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promjeniActionPerformed
        // TODO add your handling code here:
                try {
            Utakmica i = (Utakmica) lista.getSelectedValue();
            i.setRezultat(rezultat.getText());
        i.setDomacin((Ekipa)domacin.getSelectedItem());
        i.setGost((Ekipa)gost.getSelectedItem());
        i.setMjesto((Mjesto)mjesto.getSelectedItem());
        ou.promjeni(i);
            ucitaj();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, "Prvo odaberite stavku");
        }

    }//GEN-LAST:event_promjeniActionPerformed

    private void obrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obrisiActionPerformed
        // TODO add your handling code here:
                try {
            Utakmica i = (Utakmica)lista.getSelectedValue();
            ou.obrisi(i);
            ucitaj();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, "Prvo odaberite stavku");
        }

    }//GEN-LAST:event_obrisiActionPerformed

    private void listaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaValueChanged
        // TODO add your handling code here:
        try {
            Utakmica i = (Utakmica)lista.getSelectedValue();
            rezultat.setText(i.getRezultat());
            DefaultComboBoxModel m = (DefaultComboBoxModel)domacin.getModel();
            DefaultComboBoxModel a = (DefaultComboBoxModel)gost.getModel();
            DefaultComboBoxModel n = (DefaultComboBoxModel)mjesto.getModel();
        } catch (Exception e) {
        }

    }//GEN-LAST:event_listaValueChanged

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dodaj;
    private javax.swing.JComboBox<String> domacin;
    private javax.swing.JComboBox<String> gost;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Utakmica> lista;
    private javax.swing.JComboBox<String> mjesto;
    private javax.swing.JButton obrisi;
    private javax.swing.JButton promjeni;
    private javax.swing.JTextField rezultat;
    // End of variables declaration//GEN-END:variables
}
