/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ffos.rusija2018.view;
import ffos.rusija2018.controller.ObradaMjesto; 
import ffos.rusija2018.controller.ObradaEkipa;  
import ffos.rusija2018.controller.ObradaUtakmica;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.DefaultComboBoxModel;
import ffos.rusija2018.model.Utakmica;
import ffos.rusija2018.model.Ekipa;
import ffos.rusija2018.model.Mjesto;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import java.util.HashSet;
/**
 *
 * @author Sanja
 */
public class FormaMjesta extends javax.swing.JFrame {
private ObradaMjesto om;
    /**
     * Creates new form FormaMjesta
     */
    public FormaMjesta() {
        initComponents();
        
         
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);


 
om = new ObradaMjesto();


    }
    
    private void ucitaj() {
        DefaultListModel m = new DefaultListModel();
        for (Mjesto p : om.getMjesta()) {
            m.addElement(p);
        }
        lista.setModel(m);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        naziv_grada = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        naziv_stadiona = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        broj_gledatelja = new javax.swing.JTextField();
        dodaj = new javax.swing.JButton();
        promjeni = new javax.swing.JButton();
        obrisi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Rusija 2018 Mjesta");

        lista.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lista);

        jLabel1.setText("Naziv grada");

        jLabel2.setText("Naziv stadiona");

        jLabel3.setText("Broj gledatelja");

        dodaj.setText("Dodaj");
        dodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajActionPerformed(evt);
            }
        });

        promjeni.setText("Promijeni");
        promjeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promjeniActionPerformed(evt);
            }
        });

        obrisi.setText("Obriši");
        obrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obrisiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(naziv_grada)
                    .addComponent(jLabel2)
                    .addComponent(naziv_stadiona)
                    .addComponent(jLabel3)
                    .addComponent(broj_gledatelja, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(dodaj)
                    .addComponent(promjeni)
                    .addComponent(obrisi))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {broj_gledatelja, dodaj, jLabel1, jLabel2, jLabel3, naziv_grada, naziv_stadiona, obrisi, promjeni});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(naziv_grada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(naziv_stadiona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(broj_gledatelja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dodaj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(promjeni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(obrisi))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajActionPerformed
        // TODO add your handling code here:
        Mjesto p = new Mjesto();
        p.setNaziv_grada(naziv_grada.getText());
        p.setNaziv_stadiona(naziv_stadiona.getText());
        p.setBroj_gledatelja(Integer.parseInt(broj_gledatelja.getText()));
        om.dodaj(p);
        ucitaj();
    }//GEN-LAST:event_dodajActionPerformed

    private void promjeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promjeniActionPerformed
        // TODO add your handling code here:
        try {
            DefaultListModel m = (DefaultListModel)lista.getModel();
            Mjesto p = (Mjesto)m.get(lista.getSelectedIndex());
            p.setNaziv_grada(naziv_grada.getText());
        p.setNaziv_stadiona(naziv_stadiona.getText());
        p.setBroj_gledatelja(Integer.parseInt(broj_gledatelja.getText()));
        om.promjeni(p);
            ucitaj();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, "Prvo odaberite stavku");
        }
    }//GEN-LAST:event_promjeniActionPerformed

    private void obrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obrisiActionPerformed
        // TODO add your handling code here:
        try {
            DefaultListModel m = (DefaultListModel)lista.getModel();
            Mjesto p = (Mjesto)m.get(lista.getSelectedIndex());
            p.setNaziv_grada(naziv_grada.getText());
        p.setNaziv_stadiona(naziv_stadiona.getText());
        p.setBroj_gledatelja(Integer.parseInt(broj_gledatelja.getText()));
        om.obrisi(p);
            ucitaj();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, "Prvo odaberite stavku");
        }
    }//GEN-LAST:event_obrisiActionPerformed

    private void listaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaValueChanged
        // TODO add your handling code here:
                try {
            DefaultListModel m = (DefaultListModel)lista.getModel();
            Mjesto p = (Mjesto)m.get(lista.getSelectedIndex());
            
        } catch (Exception e) {
        }

    }//GEN-LAST:event_listaValueChanged

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField broj_gledatelja;
    private javax.swing.JButton dodaj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Mjesto> lista;
    private javax.swing.JTextField naziv_grada;
    private javax.swing.JTextField naziv_stadiona;
    private javax.swing.JButton obrisi;
    private javax.swing.JButton promjeni;
    // End of variables declaration//GEN-END:variables
}
