/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ffos.rusija2018.view;
import ffos.rusija2018.controller.ObradaEkipa;  
import java.awt.Dimension;
import java.awt.Toolkit;
import ffos.rusija2018.model.Ekipa;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import java.util.HashSet;

/**
 *
 * @author Sanja
 */
public class FormaEkipe extends javax.swing.JFrame {
private ObradaEkipa oe;
    /**
     * Creates new form FormaEkipa
     */
    public FormaEkipe() {
        initComponents();
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);

oe = new ObradaEkipa();
ucitaj();

    }
    
        private void ucitaj() {
        DefaultListModel m = new DefaultListModel();
        for (Ekipa p : oe.getEkipe()) {
            m.addElement(p);
        }
        lista.setModel(m);
        
        
       
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        naziv = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        izbornik = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pozicija = new javax.swing.JTextField();
        dodaj = new javax.swing.JButton();
        promjeni = new javax.swing.JButton();
        obrisi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Rusija 2018 Ekipe");

        lista.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lista);

        jLabel1.setText("Naziv");

        jLabel2.setText("Izbornik");

        jLabel3.setText("Pozicija");

        dodaj.setText("Dodaj");
        dodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajActionPerformed(evt);
            }
        });

        promjeni.setText("Promijeni");
        promjeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promjeniActionPerformed(evt);
            }
        });

        obrisi.setText("Obriši");
        obrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obrisiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(naziv)
                        .addComponent(jLabel2)
                        .addComponent(izbornik)
                        .addComponent(jLabel3)
                        .addComponent(pozicija, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
                    .addComponent(dodaj)
                    .addComponent(promjeni)
                    .addComponent(obrisi))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {dodaj, izbornik, jLabel1, jLabel2, jLabel3, naziv, obrisi, pozicija, promjeni});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(naziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(izbornik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pozicija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(dodaj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(promjeni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(obrisi))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajActionPerformed
        // TODO add your handling code here:
        Ekipa p = new Ekipa();
        p.setNaziv(naziv.getText());
        p.setIzbornik(izbornik.getText());
        p.setPozicija(pozicija.getText());
        oe.dodaj(p);
        ucitaj();

    }//GEN-LAST:event_dodajActionPerformed

    private void promjeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promjeniActionPerformed
        // TODO add your handling code here:
                try {
            DefaultListModel m = (DefaultListModel)lista.getModel();
            Ekipa p = (Ekipa)m.get(lista.getSelectedIndex());
            p.setNaziv(naziv.getText());
            p.setIzbornik(izbornik.getText());
        p.setPozicija(pozicija.getText());
            oe.promjeni(p);
            ucitaj();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, "Prvo odaberite stavku");
        }

    }//GEN-LAST:event_promjeniActionPerformed

    private void obrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obrisiActionPerformed
        // TODO add your handling code here:
        try {
            DefaultListModel m = (DefaultListModel)lista.getModel();
            Ekipa p = (Ekipa)m.get(lista.getSelectedIndex());
            p.setNaziv(naziv.getText());
            p.setIzbornik(izbornik.getText());
        p.setPozicija(pozicija.getText());
            oe.obrisi(p);
            ucitaj();
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, "Prvo odaberite stavku");
        }

    }//GEN-LAST:event_obrisiActionPerformed

    private void listaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaValueChanged
        // TODO add your handling code here:
                try {
            DefaultListModel m = (DefaultListModel)lista.getModel();
            Ekipa p = (Ekipa)m.get(lista.getSelectedIndex());
            naziv.setText(p.getNaziv());
            izbornik.setText(p.getIzbornik());
            pozicija.setText(p.getPozicija());
        } catch (Exception e) {
        }

    }//GEN-LAST:event_listaValueChanged

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dodaj;
    private javax.swing.JTextField izbornik;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Ekipa> lista;
    private javax.swing.JTextField naziv;
    private javax.swing.JButton obrisi;
    private javax.swing.JTextField pozicija;
    private javax.swing.JButton promjeni;
    // End of variables declaration//GEN-END:variables
}
