/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ffos.rusija2018.view;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Sanja
 */
public class Izbornik extends javax.swing.JFrame {

    /**
     * Creates new form Izbornik
     */
    public Izbornik() {
        initComponents();
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ekipe = new javax.swing.JButton();
        mjesta = new javax.swing.JButton();
        utakmice = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Izbornik");

        ekipe.setText("Ekipe");
        ekipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekipeActionPerformed(evt);
            }
        });

        mjesta.setText("Mjesta");
        mjesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mjestaActionPerformed(evt);
            }
        });

        utakmice.setText("Utakmice");
        utakmice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utakmiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(ekipe)
                        .addGap(72, 72, 72)
                        .addComponent(mjesta))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(utakmice)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ekipe)
                    .addComponent(mjesta))
                .addGap(65, 65, 65)
                .addComponent(utakmice)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ekipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekipeActionPerformed
        // TODO add your handling code here:
        new FormaEkipe().setVisible(true);
    }//GEN-LAST:event_ekipeActionPerformed

    private void mjestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mjestaActionPerformed
        // TODO add your handling code here:
        new FormaMjesta().setVisible(true);
    }//GEN-LAST:event_mjestaActionPerformed

    private void utakmiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utakmiceActionPerformed
        // TODO add your handling code here:
        new FormaUtakmice().setVisible(true);
    }//GEN-LAST:event_utakmiceActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ekipe;
    private javax.swing.JButton mjesta;
    private javax.swing.JButton utakmice;
    // End of variables declaration//GEN-END:variables
}
